# Generated by Django 3.0.5 on 2020-05-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200515_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
